name: learnskill
description: Pixel-perfect native iOS-style homepage as shown in the PNG.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.20.2
  flutter_platform_widgets: ^2.0.0
  flutter_svg: ^2.0.9
  shared_preferences: ^2.2.2
  logging: ^1.2.0
  http: ^1.5.0
  pdf: ^3.11.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: false
  
  assets:
    - assets/meat_icon.svg
    - assets/veg_icon.svg
    - assets/arrow.svg